export const pricingPlans = [
  {
    name: "Starter",
    monthlyPrice: 554,
    monthlyDiscount: 10,
    annualPrice: 410,
    annualDiscount: 15,
    threeYearPrice: 0,
    threeYearDiscount: 0,
    users: "Up to 1 user",
    storage: "1 GB Cloud Storage",
    support: "Email Support",
    potential: "12%",
    chartColor: "teal",
    chartData: [10, 15, 12, 18, 22, 19, 25, 30, 28, 35, 40, 38, 42],
    features: {
      monthly: [
        "Daily Trading View & Strategy Analysis",
        "Basic AI Alerts for Key Market Moves",
        "Daily Index Analysis",
        "Weekly Swing Trades",
        "Weekly Investment Ideas",
        "Get Positional Trade Ideas",
        "Access to Peer Learning Forum",
      ],
      yearly: [
        "Daily Trading Strategies & Market Trends",
        "Personalized AI Signals for Entry & Exit",
        "Daily Market Updates & Alerts",
        "6-Month Full Access ",
        "Networking Events + Mentorship Access",
        "Advanced Beginner Tutorials (RSI, MACD)",
        "Automated Suggestions for Risk Management",
        "Enhanced Screener for Sector Analysis",
        "Advanced Portfolio Testing Modules",
        "Monthly Webinars on Key Trading Concepts",
        "Full Year Access to All Beginner Courses",
      ],
    },
  },
  {
    name: "Trader",
    monthlyPrice: 1703,
    monthlyDiscount: 12,
    annualPrice: 1499,
    annualDiscount: 20,
    threeYearPrice: 0,
    threeYearDiscount: 0,
    users: "Up to 3 users",
    storage: "10 GB Cloud Storage",
    support: "Priority Email Support",
    potential: "21%",
    chartColor: "pink",
    chartData: [15, 20, 18, 25, 30, 28, 35, 45, 50, 48, 55, 60, 65],
    features: {
      monthly: [
        "All Starter Packages are included",
        "Daily Commodities Strategies",
        "Daily Swing & Day Trading Strategies",
        "Advanced AI Alerts for Intraday Movements",
        "Daily Market Forecasts & Alerts",
        "Access Investment Ideas",
        "Gain access to Stock Research Reports",
        "Daily trading of Cryptocurrency",
        "Full 1-Month Simulation Access",
        "Introduction to Algorithmic Trading",
        "1 to 1 Mentorship with our Experts",
        "Monthly Access to Expert Webinars",
        "Advanced Trading & Investment Modules",
      ],
      yearly: [
        "In-Depth Market Analysis & Strategies",
        "Customized AI Trading Pathways ",
        "Weekly Economic Forecasts & Insights",
        "Unlimited Simulations with AI Evaluation",
        "Advanced Algorithmic Strategies & Examples",
        "Weekly Live Sessions with Market Experts",
        "Elliott Wave Theory & Fibonacci Strategies",
        "Advanced Risk Mitigation Strategies",
        "AI-Driven Allocation Adjustments",
        "Advanced Hedging & Options Strategies",
        "Masterclasses by Top Financial Analysts",
      ],
    },
  },
  {
    name: "Pro",
    monthlyPrice: 2940,
    monthlyDiscount: 15,
    annualPrice: 2799,
    annualDiscount: 25,
    threeYearPrice: 2685,
    threeYearDiscount: 33,
    users: "Unlimited users",
    storage: "50 GB Cloud Storage",
    support: "24/7 Priority Support",
    potential: "33%",
    chartColor: "green",
    chartData: [20, 25, 30, 28, 35, 40, 45, 50, 55, 60, 70, 75, 80],
    features: {
      monthly: [
        "All Starter and Trader Packages are included",
        "Advanced Options, Futures, & Stocks Tactics",
        "Daily trading of Cryptocurrency",
        "Access Portfolio Hedging Strategies",
        "Access F&O Strategies",
        "Access ETF Reports",
        "Access Premium Scanner",
        "Access to Outperforming Stocks",
        "Access to Underperforming Stocks",
        "Real-Time AI Trade Execution Insights",
        "Basic Algo Trading Scripts & Execution",
        "Advanced Stop Loss Strategies",
        "Dynamic Strategies for Volatility",
        "Weekly Expert Sessions",
      ],
      yearly: [
        "Full Market Analysis & Multi-Layer Strategies",
        "Predictive AI Models for Market Trends",
        "Full Access to Customizable Algo Trading Suite",
        "Daily Updates with Global Financial Impacts",
        "Tailored Risk Profiles & Portfolio Protection",
        "Weekly High-Level Strategy Discussions",
        "AI-Based Portfolio Optimization",
        "Elliott Wave & Advanced Volume Strategies",
        "VIP Workshops with Industry Leaders",
        "AI-Optimized Asset Allocation",
        "Continuous Learning Path with Advanced Tools",
      ],
      threeYear: [
        "Custom 3-Year Roadmap with Adaptive Strategies",
        "Personalized AI Trading System Development",
        "Exclusive Algo Trading Strategy Backtesting & Support",
        "Multi-Year Financial Forecasts & Reports",
        "Complete Risk Management Automation",
        "VIP Access to Industry Conferences & Workshops",
        "Advanced AI Trading Analytics",
        "Lifetime Access to New Indicator Releases",
        "Access to All Premium Events & Training",
        "Lifetime Access to Portfolio Review Services",
        "Comprehensive Market Study Program",
      ],
    },
  },
];
